name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://npm.pkg.github.com'

    - name: Configure npm for GitHub Packages
      run: |
        npm config set @building-for-fun:registry https://npm.pkg.github.com
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
    - name: Install dependencies
      run: npm install

    - name: Publish package
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}